// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bcdb.proto

package bcdb_proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Tag is a single entry in an object.
// The tag key must be a string, but the
// value can be either a string, double signed, or unsigned number
// Tags are always indexed, and can be used to find the associated meta
// objects later on.
type Tag struct {
	// key of the tag
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value of the tag. Only supporting few primitive types
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{0}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AclRef struct {
	Acl                  uint64   `protobuf:"varint,1,opt,name=acl,proto3" json:"acl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AclRef) Reset()         { *m = AclRef{} }
func (m *AclRef) String() string { return proto.CompactTextString(m) }
func (*AclRef) ProtoMessage()    {}
func (*AclRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{1}
}

func (m *AclRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AclRef.Unmarshal(m, b)
}
func (m *AclRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AclRef.Marshal(b, m, deterministic)
}
func (m *AclRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AclRef.Merge(m, src)
}
func (m *AclRef) XXX_Size() int {
	return xxx_messageInfo_AclRef.Size(m)
}
func (m *AclRef) XXX_DiscardUnknown() {
	xxx_messageInfo_AclRef.DiscardUnknown(m)
}

var xxx_messageInfo_AclRef proto.InternalMessageInfo

func (m *AclRef) GetAcl() uint64 {
	if m != nil {
		return m.Acl
	}
	return 0
}

// Metadata represents a set of tags (also known as Metadata)
type Metadata struct {
	// set of searchable tags.
	Tags []*Tag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	// required collection
	Collection string `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	// acl is a ref to the acl key (optional)
	Acl                  *AclRef  `protobuf:"bytes,3,opt,name=acl,proto3" json:"acl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{2}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Metadata) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *Metadata) GetAcl() *AclRef {
	if m != nil {
		return m.Acl
	}
	return nil
}

// Set request
type SetRequest struct {
	Metadata             *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data                 []byte    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{3}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *SetRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Set response
type SetResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{4}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Get request
type GetRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

// Get response
type GetResponse struct {
	Metadata             *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data                 []byte    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{6}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *GetResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Update request
type UpdateRequest struct {
	Id                   uint32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata             *Metadata                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data                 *UpdateRequest_UpdateData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *UpdateRequest) GetData() *UpdateRequest_UpdateData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateRequest_UpdateData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest_UpdateData) Reset()         { *m = UpdateRequest_UpdateData{} }
func (m *UpdateRequest_UpdateData) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest_UpdateData) ProtoMessage()    {}
func (*UpdateRequest_UpdateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{7, 0}
}

func (m *UpdateRequest_UpdateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest_UpdateData.Unmarshal(m, b)
}
func (m *UpdateRequest_UpdateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest_UpdateData.Marshal(b, m, deterministic)
}
func (m *UpdateRequest_UpdateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest_UpdateData.Merge(m, src)
}
func (m *UpdateRequest_UpdateData) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest_UpdateData.Size(m)
}
func (m *UpdateRequest_UpdateData) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest_UpdateData.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest_UpdateData proto.InternalMessageInfo

func (m *UpdateRequest_UpdateData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Update response
type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{8}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

// Query request for finding entries
type QueryRequest struct {
	Collection           string   `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{9}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *QueryRequest) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

// List response
type ListResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{10}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Find response
type FindResponse struct {
	Id                   uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{11}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FindResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ACL struct {
	Perm                 string   `protobuf:"bytes,1,opt,name=perm,proto3" json:"perm,omitempty"`
	Users                []uint64 `protobuf:"varint,2,rep,packed,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACL) Reset()         { *m = ACL{} }
func (m *ACL) String() string { return proto.CompactTextString(m) }
func (*ACL) ProtoMessage()    {}
func (*ACL) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{12}
}

func (m *ACL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACL.Unmarshal(m, b)
}
func (m *ACL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACL.Marshal(b, m, deterministic)
}
func (m *ACL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACL.Merge(m, src)
}
func (m *ACL) XXX_Size() int {
	return xxx_messageInfo_ACL.Size(m)
}
func (m *ACL) XXX_DiscardUnknown() {
	xxx_messageInfo_ACL.DiscardUnknown(m)
}

var xxx_messageInfo_ACL proto.InternalMessageInfo

func (m *ACL) GetPerm() string {
	if m != nil {
		return m.Perm
	}
	return ""
}

func (m *ACL) GetUsers() []uint64 {
	if m != nil {
		return m.Users
	}
	return nil
}

type ACLGetRequest struct {
	Key                  uint32   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACLGetRequest) Reset()         { *m = ACLGetRequest{} }
func (m *ACLGetRequest) String() string { return proto.CompactTextString(m) }
func (*ACLGetRequest) ProtoMessage()    {}
func (*ACLGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{13}
}

func (m *ACLGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLGetRequest.Unmarshal(m, b)
}
func (m *ACLGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLGetRequest.Marshal(b, m, deterministic)
}
func (m *ACLGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLGetRequest.Merge(m, src)
}
func (m *ACLGetRequest) XXX_Size() int {
	return xxx_messageInfo_ACLGetRequest.Size(m)
}
func (m *ACLGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ACLGetRequest proto.InternalMessageInfo

func (m *ACLGetRequest) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

type ACLGetResponse struct {
	Acl                  *ACL     `protobuf:"bytes,1,opt,name=acl,proto3" json:"acl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACLGetResponse) Reset()         { *m = ACLGetResponse{} }
func (m *ACLGetResponse) String() string { return proto.CompactTextString(m) }
func (*ACLGetResponse) ProtoMessage()    {}
func (*ACLGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{14}
}

func (m *ACLGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLGetResponse.Unmarshal(m, b)
}
func (m *ACLGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLGetResponse.Marshal(b, m, deterministic)
}
func (m *ACLGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLGetResponse.Merge(m, src)
}
func (m *ACLGetResponse) XXX_Size() int {
	return xxx_messageInfo_ACLGetResponse.Size(m)
}
func (m *ACLGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ACLGetResponse proto.InternalMessageInfo

func (m *ACLGetResponse) GetAcl() *ACL {
	if m != nil {
		return m.Acl
	}
	return nil
}

type ACLCreateRequest struct {
	Acl                  *ACL     `protobuf:"bytes,1,opt,name=acl,proto3" json:"acl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACLCreateRequest) Reset()         { *m = ACLCreateRequest{} }
func (m *ACLCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ACLCreateRequest) ProtoMessage()    {}
func (*ACLCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{15}
}

func (m *ACLCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLCreateRequest.Unmarshal(m, b)
}
func (m *ACLCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLCreateRequest.Marshal(b, m, deterministic)
}
func (m *ACLCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLCreateRequest.Merge(m, src)
}
func (m *ACLCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ACLCreateRequest.Size(m)
}
func (m *ACLCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ACLCreateRequest proto.InternalMessageInfo

func (m *ACLCreateRequest) GetAcl() *ACL {
	if m != nil {
		return m.Acl
	}
	return nil
}

type ACLCreateResponse struct {
	Key                  uint32   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACLCreateResponse) Reset()         { *m = ACLCreateResponse{} }
func (m *ACLCreateResponse) String() string { return proto.CompactTextString(m) }
func (*ACLCreateResponse) ProtoMessage()    {}
func (*ACLCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{16}
}

func (m *ACLCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLCreateResponse.Unmarshal(m, b)
}
func (m *ACLCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLCreateResponse.Marshal(b, m, deterministic)
}
func (m *ACLCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLCreateResponse.Merge(m, src)
}
func (m *ACLCreateResponse) XXX_Size() int {
	return xxx_messageInfo_ACLCreateResponse.Size(m)
}
func (m *ACLCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ACLCreateResponse proto.InternalMessageInfo

func (m *ACLCreateResponse) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

type ACLListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACLListRequest) Reset()         { *m = ACLListRequest{} }
func (m *ACLListRequest) String() string { return proto.CompactTextString(m) }
func (*ACLListRequest) ProtoMessage()    {}
func (*ACLListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{17}
}

func (m *ACLListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLListRequest.Unmarshal(m, b)
}
func (m *ACLListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLListRequest.Marshal(b, m, deterministic)
}
func (m *ACLListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLListRequest.Merge(m, src)
}
func (m *ACLListRequest) XXX_Size() int {
	return xxx_messageInfo_ACLListRequest.Size(m)
}
func (m *ACLListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ACLListRequest proto.InternalMessageInfo

type ACLListResponse struct {
	Key                  uint32   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Acl                  *ACL     `protobuf:"bytes,2,opt,name=acl,proto3" json:"acl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACLListResponse) Reset()         { *m = ACLListResponse{} }
func (m *ACLListResponse) String() string { return proto.CompactTextString(m) }
func (*ACLListResponse) ProtoMessage()    {}
func (*ACLListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{18}
}

func (m *ACLListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLListResponse.Unmarshal(m, b)
}
func (m *ACLListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLListResponse.Marshal(b, m, deterministic)
}
func (m *ACLListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLListResponse.Merge(m, src)
}
func (m *ACLListResponse) XXX_Size() int {
	return xxx_messageInfo_ACLListResponse.Size(m)
}
func (m *ACLListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ACLListResponse proto.InternalMessageInfo

func (m *ACLListResponse) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *ACLListResponse) GetAcl() *ACL {
	if m != nil {
		return m.Acl
	}
	return nil
}

type ACLSetRequest struct {
	Key                  uint32   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Perm                 string   `protobuf:"bytes,2,opt,name=perm,proto3" json:"perm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACLSetRequest) Reset()         { *m = ACLSetRequest{} }
func (m *ACLSetRequest) String() string { return proto.CompactTextString(m) }
func (*ACLSetRequest) ProtoMessage()    {}
func (*ACLSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{19}
}

func (m *ACLSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLSetRequest.Unmarshal(m, b)
}
func (m *ACLSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLSetRequest.Marshal(b, m, deterministic)
}
func (m *ACLSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLSetRequest.Merge(m, src)
}
func (m *ACLSetRequest) XXX_Size() int {
	return xxx_messageInfo_ACLSetRequest.Size(m)
}
func (m *ACLSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ACLSetRequest proto.InternalMessageInfo

func (m *ACLSetRequest) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *ACLSetRequest) GetPerm() string {
	if m != nil {
		return m.Perm
	}
	return ""
}

type ACLSetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACLSetResponse) Reset()         { *m = ACLSetResponse{} }
func (m *ACLSetResponse) String() string { return proto.CompactTextString(m) }
func (*ACLSetResponse) ProtoMessage()    {}
func (*ACLSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{20}
}

func (m *ACLSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLSetResponse.Unmarshal(m, b)
}
func (m *ACLSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLSetResponse.Marshal(b, m, deterministic)
}
func (m *ACLSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLSetResponse.Merge(m, src)
}
func (m *ACLSetResponse) XXX_Size() int {
	return xxx_messageInfo_ACLSetResponse.Size(m)
}
func (m *ACLSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ACLSetResponse proto.InternalMessageInfo

type ACLUsersRequest struct {
	Key                  uint32   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Users                []uint64 `protobuf:"varint,2,rep,packed,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACLUsersRequest) Reset()         { *m = ACLUsersRequest{} }
func (m *ACLUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ACLUsersRequest) ProtoMessage()    {}
func (*ACLUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{21}
}

func (m *ACLUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLUsersRequest.Unmarshal(m, b)
}
func (m *ACLUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLUsersRequest.Marshal(b, m, deterministic)
}
func (m *ACLUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLUsersRequest.Merge(m, src)
}
func (m *ACLUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ACLUsersRequest.Size(m)
}
func (m *ACLUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ACLUsersRequest proto.InternalMessageInfo

func (m *ACLUsersRequest) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *ACLUsersRequest) GetUsers() []uint64 {
	if m != nil {
		return m.Users
	}
	return nil
}

type ACLUsersResponse struct {
	Updated              uint64   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACLUsersResponse) Reset()         { *m = ACLUsersResponse{} }
func (m *ACLUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ACLUsersResponse) ProtoMessage()    {}
func (*ACLUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b705b2a83eae7f, []int{22}
}

func (m *ACLUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLUsersResponse.Unmarshal(m, b)
}
func (m *ACLUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLUsersResponse.Marshal(b, m, deterministic)
}
func (m *ACLUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLUsersResponse.Merge(m, src)
}
func (m *ACLUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ACLUsersResponse.Size(m)
}
func (m *ACLUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ACLUsersResponse proto.InternalMessageInfo

func (m *ACLUsersResponse) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func init() {
	proto.RegisterType((*Tag)(nil), "bcdb.Tag")
	proto.RegisterType((*AclRef)(nil), "bcdb.AclRef")
	proto.RegisterType((*Metadata)(nil), "bcdb.Metadata")
	proto.RegisterType((*SetRequest)(nil), "bcdb.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "bcdb.SetResponse")
	proto.RegisterType((*GetRequest)(nil), "bcdb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "bcdb.GetResponse")
	proto.RegisterType((*UpdateRequest)(nil), "bcdb.UpdateRequest")
	proto.RegisterType((*UpdateRequest_UpdateData)(nil), "bcdb.UpdateRequest.UpdateData")
	proto.RegisterType((*UpdateResponse)(nil), "bcdb.UpdateResponse")
	proto.RegisterType((*QueryRequest)(nil), "bcdb.QueryRequest")
	proto.RegisterType((*ListResponse)(nil), "bcdb.ListResponse")
	proto.RegisterType((*FindResponse)(nil), "bcdb.FindResponse")
	proto.RegisterType((*ACL)(nil), "bcdb.ACL")
	proto.RegisterType((*ACLGetRequest)(nil), "bcdb.ACLGetRequest")
	proto.RegisterType((*ACLGetResponse)(nil), "bcdb.ACLGetResponse")
	proto.RegisterType((*ACLCreateRequest)(nil), "bcdb.ACLCreateRequest")
	proto.RegisterType((*ACLCreateResponse)(nil), "bcdb.ACLCreateResponse")
	proto.RegisterType((*ACLListRequest)(nil), "bcdb.ACLListRequest")
	proto.RegisterType((*ACLListResponse)(nil), "bcdb.ACLListResponse")
	proto.RegisterType((*ACLSetRequest)(nil), "bcdb.ACLSetRequest")
	proto.RegisterType((*ACLSetResponse)(nil), "bcdb.ACLSetResponse")
	proto.RegisterType((*ACLUsersRequest)(nil), "bcdb.ACLUsersRequest")
	proto.RegisterType((*ACLUsersResponse)(nil), "bcdb.ACLUsersResponse")
}

func init() {
	proto.RegisterFile("bcdb.proto", fileDescriptor_41b705b2a83eae7f)
}

var fileDescriptor_41b705b2a83eae7f = []byte{
	// 658 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xd9, 0x6a, 0xdb, 0x4c,
	0x14, 0x8e, 0x96, 0xf8, 0x4f, 0x8e, 0x97, 0xdf, 0x99, 0xa4, 0xa9, 0x51, 0x89, 0x71, 0x07, 0x0a,
	0xa1, 0x64, 0x29, 0x2a, 0xa1, 0x0d, 0xed, 0x45, 0x15, 0x85, 0x0a, 0x8a, 0x7c, 0x51, 0x39, 0x79,
	0x00, 0x59, 0x9a, 0x1a, 0x11, 0xc5, 0x72, 0x25, 0x39, 0x90, 0xcb, 0x3e, 0x4a, 0xdf, 0xaa, 0x8f,
	0x53, 0x66, 0x91, 0x34, 0xf2, 0x16, 0x42, 0xef, 0x66, 0xce, 0x9c, 0xef, 0x9c, 0xef, 0x3b, 0x8b,
	0x04, 0x30, 0x0e, 0xc2, 0xf1, 0xd9, 0x2c, 0x4d, 0xf2, 0x04, 0xe9, 0xf4, 0x8c, 0x4f, 0x41, 0xbb,
	0xf1, 0x27, 0xa8, 0x0b, 0xda, 0x1d, 0x79, 0xec, 0x29, 0x03, 0xe5, 0x78, 0xd7, 0xa3, 0x47, 0x74,
	0x00, 0xdb, 0x0f, 0x7e, 0x3c, 0x27, 0x3d, 0x95, 0xd9, 0xf8, 0x05, 0x1b, 0xd0, 0xb0, 0x82, 0xd8,
	0x23, 0x3f, 0x28, 0xc2, 0x0f, 0x62, 0x86, 0xd0, 0x3d, 0x7a, 0xc4, 0x11, 0xec, 0x0c, 0x49, 0xee,
	0x87, 0x7e, 0xee, 0xa3, 0x23, 0xd0, 0x73, 0x7f, 0x92, 0xf5, 0x94, 0x81, 0x76, 0xdc, 0x34, 0x77,
	0xcf, 0x58, 0xde, 0x1b, 0x7f, 0xe2, 0x31, 0x33, 0xea, 0x03, 0x04, 0x49, 0x1c, 0x93, 0x20, 0x8f,
	0x92, 0xa9, 0xc8, 0x20, 0x59, 0x50, 0x9f, 0x07, 0xd7, 0x06, 0xca, 0x71, 0xd3, 0x6c, 0x71, 0x34,
	0xcf, 0xcb, 0x53, 0xb9, 0x00, 0x23, 0x92, 0x7b, 0xe4, 0xe7, 0x9c, 0x64, 0x39, 0x7a, 0x0b, 0x3b,
	0xf7, 0x22, 0x31, 0xe3, 0xd3, 0x34, 0x3b, 0x1c, 0x52, 0xd0, 0xf1, 0xca, 0x77, 0x84, 0x40, 0x67,
	0x7e, 0x34, 0x67, 0xcb, 0x63, 0x67, 0x7c, 0x04, 0x4d, 0x16, 0x2d, 0x9b, 0x25, 0xd3, 0x8c, 0xa0,
	0x0e, 0xa8, 0x51, 0xc8, 0x02, 0xb5, 0x3d, 0x35, 0x0a, 0xf1, 0x67, 0x00, 0xa7, 0x4a, 0xb6, 0xf0,
	0xfa, 0x94, 0x14, 0x3c, 0x84, 0xa6, 0x23, 0x05, 0xff, 0x57, 0xae, 0xbf, 0x15, 0x68, 0xdf, 0xce,
	0x42, 0x3f, 0x27, 0xeb, 0x08, 0xc9, 0x19, 0xd4, 0x27, 0x32, 0x98, 0x22, 0x03, 0x2f, 0x74, 0x9f,
	0xfb, 0xd5, 0xc2, 0x8b, 0xdb, 0x35, 0xc5, 0x31, 0x5f, 0x63, 0x00, 0x50, 0xd9, 0x4a, 0x8e, 0x8a,
	0xc4, 0xb1, 0x0b, 0x9d, 0x22, 0x06, 0x57, 0x8d, 0x87, 0xd0, 0xfa, 0x3e, 0x27, 0xe9, 0x63, 0xc1,
	0xb9, 0x5e, 0x34, 0x65, 0xa9, 0xff, 0xc5, 0xf8, 0xa8, 0x2b, 0xc7, 0x07, 0xf7, 0xa1, 0xe5, 0x46,
	0xd9, 0xfa, 0x8e, 0x7d, 0x83, 0xd6, 0xd7, 0x68, 0x1a, 0xae, 0x7b, 0x7f, 0x4e, 0x89, 0xf0, 0x39,
	0x68, 0x96, 0xed, 0x52, 0x9d, 0x33, 0x92, 0xde, 0x0b, 0xae, 0xec, 0x4c, 0x57, 0x64, 0x9e, 0x91,
	0x94, 0xd3, 0xd4, 0x3d, 0x7e, 0xc1, 0xaf, 0xa1, 0x6d, 0xd9, 0xae, 0x34, 0x31, 0xd2, 0x6e, 0xb5,
	0xd9, 0x6e, 0xe1, 0x53, 0xe8, 0x14, 0x2e, 0x82, 0xe1, 0xab, 0x6a, 0x9b, 0x4a, 0xbd, 0x96, 0xed,
	0xf2, 0x69, 0x3f, 0x87, 0xae, 0x65, 0xbb, 0x76, 0x4a, 0xa4, 0xae, 0x6f, 0x04, 0xbc, 0x81, 0x3d,
	0x09, 0x20, 0x52, 0x2c, 0xd3, 0xe8, 0x32, 0x1a, 0xbc, 0x92, 0x2c, 0x2a, 0xfe, 0x02, 0xff, 0x97,
	0x96, 0x75, 0xb0, 0x22, 0xb5, 0xba, 0x32, 0xf5, 0x05, 0x53, 0x3f, 0xda, 0xa0, 0xbe, 0x2c, 0xa5,
	0x5a, 0x95, 0x52, 0x50, 0x91, 0xb6, 0x10, 0x5f, 0x32, 0x2a, 0xb7, 0xb4, 0xa4, 0xeb, 0x43, 0xad,
	0xee, 0xc0, 0x09, 0xab, 0x97, 0x80, 0x0a, 0x19, 0x3d, 0xf8, 0x6f, 0xce, 0x66, 0x32, 0x14, 0x9f,
	0xac, 0xe2, 0x6a, 0xfe, 0x52, 0x41, 0xbf, 0xb2, 0xaf, 0xaf, 0xd0, 0x09, 0x68, 0x23, 0x92, 0xa3,
	0x2e, 0x57, 0x54, 0x49, 0x30, 0xf6, 0x24, 0x8b, 0x60, 0xb7, 0x45, 0xbd, 0x9d, 0xca, 0xdb, 0x59,
	0xf2, 0x76, 0x6a, 0xde, 0x17, 0xd0, 0xe0, 0x2b, 0x81, 0xf6, 0x57, 0x2c, 0x99, 0x71, 0x50, 0x37,
	0x96, 0x30, 0x13, 0x74, 0xda, 0x0c, 0x84, 0xf8, 0xbb, 0xbc, 0x43, 0x86, 0xb0, 0xc9, 0xcd, 0xc2,
	0x5b, 0xef, 0x14, 0x8a, 0xa1, 0xc3, 0xbf, 0x09, 0x23, 0x2f, 0x07, 0xc5, 0x98, 0x7f, 0x54, 0xd0,
	0xac, 0x20, 0x46, 0x26, 0x17, 0xb5, 0x5f, 0x36, 0x55, 0xd2, 0x75, 0x50, 0x37, 0x96, 0x1c, 0x3f,
	0x41, 0x83, 0x4f, 0x1a, 0x3a, 0x2c, 0x3d, 0x6a, 0xb3, 0x6a, 0xbc, 0x5c, 0xb2, 0x97, 0xe0, 0x0f,
	0x42, 0x60, 0x15, 0x5c, 0x1a, 0x47, 0xe3, 0xc5, 0x82, 0xb5, 0xa6, 0x92, 0x35, 0xab, 0x62, 0x3a,
	0x5a, 0xc5, 0xb4, 0xde, 0xb2, 0x8f, 0xb0, 0xed, 0xa4, 0xfe, 0x34, 0x47, 0x55, 0x5c, 0x79, 0xbe,
	0x8c, 0xc3, 0x45, 0x73, 0x89, 0xbc, 0x84, 0x86, 0x47, 0x1e, 0x92, 0x3b, 0xf2, 0x6c, 0xe8, 0xb8,
	0xc1, 0xfe, 0xb6, 0xef, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x57, 0xcb, 0x16, 0x7b, 0x07,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BCDBClient is the client API for BCDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BCDBClient interface {
	// Set stores a document and return a header
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	// Get a document from header
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Modify updates a document meta
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// List returns a list of document IDs that matches a query
	List(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (BCDB_ListClient, error)
	// Find like list but return full documents
	Find(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (BCDB_FindClient, error)
}

type bCDBClient struct {
	cc grpc.ClientConnInterface
}

func NewBCDBClient(cc grpc.ClientConnInterface) BCDBClient {
	return &bCDBClient{cc}
}

func (c *bCDBClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/bcdb.BCDB/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bCDBClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/bcdb.BCDB/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bCDBClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/bcdb.BCDB/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bCDBClient) List(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (BCDB_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BCDB_serviceDesc.Streams[0], "/bcdb.BCDB/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &bCDBListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BCDB_ListClient interface {
	Recv() (*ListResponse, error)
	grpc.ClientStream
}

type bCDBListClient struct {
	grpc.ClientStream
}

func (x *bCDBListClient) Recv() (*ListResponse, error) {
	m := new(ListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bCDBClient) Find(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (BCDB_FindClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BCDB_serviceDesc.Streams[1], "/bcdb.BCDB/Find", opts...)
	if err != nil {
		return nil, err
	}
	x := &bCDBFindClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BCDB_FindClient interface {
	Recv() (*FindResponse, error)
	grpc.ClientStream
}

type bCDBFindClient struct {
	grpc.ClientStream
}

func (x *bCDBFindClient) Recv() (*FindResponse, error) {
	m := new(FindResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BCDBServer is the server API for BCDB service.
type BCDBServer interface {
	// Set stores a document and return a header
	Set(context.Context, *SetRequest) (*SetResponse, error)
	// Get a document from header
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Modify updates a document meta
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// List returns a list of document IDs that matches a query
	List(*QueryRequest, BCDB_ListServer) error
	// Find like list but return full documents
	Find(*QueryRequest, BCDB_FindServer) error
}

// UnimplementedBCDBServer can be embedded to have forward compatible implementations.
type UnimplementedBCDBServer struct {
}

func (*UnimplementedBCDBServer) Set(ctx context.Context, req *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedBCDBServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBCDBServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBCDBServer) List(req *QueryRequest, srv BCDB_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedBCDBServer) Find(req *QueryRequest, srv BCDB_FindServer) error {
	return status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterBCDBServer(s *grpc.Server, srv BCDBServer) {
	s.RegisterService(&_BCDB_serviceDesc, srv)
}

func _BCDB_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BCDBServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bcdb.BCDB/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BCDBServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BCDB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BCDBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bcdb.BCDB/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BCDBServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BCDB_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BCDBServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bcdb.BCDB/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BCDBServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BCDB_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BCDBServer).List(m, &bCDBListServer{stream})
}

type BCDB_ListServer interface {
	Send(*ListResponse) error
	grpc.ServerStream
}

type bCDBListServer struct {
	grpc.ServerStream
}

func (x *bCDBListServer) Send(m *ListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BCDB_Find_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BCDBServer).Find(m, &bCDBFindServer{stream})
}

type BCDB_FindServer interface {
	Send(*FindResponse) error
	grpc.ServerStream
}

type bCDBFindServer struct {
	grpc.ServerStream
}

func (x *bCDBFindServer) Send(m *FindResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _BCDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bcdb.BCDB",
	HandlerType: (*BCDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _BCDB_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BCDB_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BCDB_Update_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _BCDB_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Find",
			Handler:       _BCDB_Find_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bcdb.proto",
}

// AclClient is the client API for Acl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AclClient interface {
	Get(ctx context.Context, in *ACLGetRequest, opts ...grpc.CallOption) (*ACLGetResponse, error)
	Create(ctx context.Context, in *ACLCreateRequest, opts ...grpc.CallOption) (*ACLCreateResponse, error)
	List(ctx context.Context, in *ACLListRequest, opts ...grpc.CallOption) (Acl_ListClient, error)
	Set(ctx context.Context, in *ACLSetRequest, opts ...grpc.CallOption) (*ACLSetResponse, error)
	Grant(ctx context.Context, in *ACLUsersRequest, opts ...grpc.CallOption) (*ACLUsersResponse, error)
	Revoke(ctx context.Context, in *ACLUsersRequest, opts ...grpc.CallOption) (*ACLUsersResponse, error)
}

type aclClient struct {
	cc grpc.ClientConnInterface
}

func NewAclClient(cc grpc.ClientConnInterface) AclClient {
	return &aclClient{cc}
}

func (c *aclClient) Get(ctx context.Context, in *ACLGetRequest, opts ...grpc.CallOption) (*ACLGetResponse, error) {
	out := new(ACLGetResponse)
	err := c.cc.Invoke(ctx, "/bcdb.Acl/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclClient) Create(ctx context.Context, in *ACLCreateRequest, opts ...grpc.CallOption) (*ACLCreateResponse, error) {
	out := new(ACLCreateResponse)
	err := c.cc.Invoke(ctx, "/bcdb.Acl/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclClient) List(ctx context.Context, in *ACLListRequest, opts ...grpc.CallOption) (Acl_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Acl_serviceDesc.Streams[0], "/bcdb.Acl/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &aclListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Acl_ListClient interface {
	Recv() (*ACLListResponse, error)
	grpc.ClientStream
}

type aclListClient struct {
	grpc.ClientStream
}

func (x *aclListClient) Recv() (*ACLListResponse, error) {
	m := new(ACLListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aclClient) Set(ctx context.Context, in *ACLSetRequest, opts ...grpc.CallOption) (*ACLSetResponse, error) {
	out := new(ACLSetResponse)
	err := c.cc.Invoke(ctx, "/bcdb.Acl/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclClient) Grant(ctx context.Context, in *ACLUsersRequest, opts ...grpc.CallOption) (*ACLUsersResponse, error) {
	out := new(ACLUsersResponse)
	err := c.cc.Invoke(ctx, "/bcdb.Acl/Grant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclClient) Revoke(ctx context.Context, in *ACLUsersRequest, opts ...grpc.CallOption) (*ACLUsersResponse, error) {
	out := new(ACLUsersResponse)
	err := c.cc.Invoke(ctx, "/bcdb.Acl/Revoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AclServer is the server API for Acl service.
type AclServer interface {
	Get(context.Context, *ACLGetRequest) (*ACLGetResponse, error)
	Create(context.Context, *ACLCreateRequest) (*ACLCreateResponse, error)
	List(*ACLListRequest, Acl_ListServer) error
	Set(context.Context, *ACLSetRequest) (*ACLSetResponse, error)
	Grant(context.Context, *ACLUsersRequest) (*ACLUsersResponse, error)
	Revoke(context.Context, *ACLUsersRequest) (*ACLUsersResponse, error)
}

// UnimplementedAclServer can be embedded to have forward compatible implementations.
type UnimplementedAclServer struct {
}

func (*UnimplementedAclServer) Get(ctx context.Context, req *ACLGetRequest) (*ACLGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedAclServer) Create(ctx context.Context, req *ACLCreateRequest) (*ACLCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAclServer) List(req *ACLListRequest, srv Acl_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedAclServer) Set(ctx context.Context, req *ACLSetRequest) (*ACLSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedAclServer) Grant(ctx context.Context, req *ACLUsersRequest) (*ACLUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Grant not implemented")
}
func (*UnimplementedAclServer) Revoke(ctx context.Context, req *ACLUsersRequest) (*ACLUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}

func RegisterAclServer(s *grpc.Server, srv AclServer) {
	s.RegisterService(&_Acl_serviceDesc, srv)
}

func _Acl_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AclServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bcdb.Acl/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AclServer).Get(ctx, req.(*ACLGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acl_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AclServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bcdb.Acl/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AclServer).Create(ctx, req.(*ACLCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acl_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ACLListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AclServer).List(m, &aclListServer{stream})
}

type Acl_ListServer interface {
	Send(*ACLListResponse) error
	grpc.ServerStream
}

type aclListServer struct {
	grpc.ServerStream
}

func (x *aclListServer) Send(m *ACLListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Acl_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AclServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bcdb.Acl/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AclServer).Set(ctx, req.(*ACLSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acl_Grant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AclServer).Grant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bcdb.Acl/Grant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AclServer).Grant(ctx, req.(*ACLUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acl_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AclServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bcdb.Acl/Revoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AclServer).Revoke(ctx, req.(*ACLUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Acl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bcdb.Acl",
	HandlerType: (*AclServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Acl_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Acl_Create_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Acl_Set_Handler,
		},
		{
			MethodName: "Grant",
			Handler:    _Acl_Grant_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _Acl_Revoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Acl_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bcdb.proto",
}
